"""add_substitution_and_return_fields_to_supplier_order_items

Revision ID: 1ef3916e8491
Revises: b89098cb0e17
Create Date: 2025-12-06 17:56:12.391403

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1ef3916e8491'
down_revision: Union[str, None] = 'b89098cb0e17'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('supplier_order_items', sa.Column('product_received_id', sa.Integer(), nullable=True))
    op.add_column('supplier_order_items', sa.Column('substitution_reason', sa.Text(), nullable=True))
    op.add_column('supplier_order_items', sa.Column('is_returned', sa.Boolean(), nullable=True, server_default='false'))
    op.add_column('supplier_order_items', sa.Column('return_quantity', sa.Integer(), nullable=True, server_default='0'))
    op.add_column('supplier_order_items', sa.Column('return_reason', sa.Text(), nullable=True))
    op.add_column('supplier_order_items', sa.Column('return_date', sa.DateTime(timezone=True), nullable=True))
    op.add_column('supplier_order_items', sa.Column('received_at', sa.DateTime(timezone=True), nullable=True))
    
    # Mettre à jour les valeurs existantes
    op.execute("UPDATE supplier_order_items SET is_returned = false WHERE is_returned IS NULL")
    op.execute("UPDATE supplier_order_items SET return_quantity = 0 WHERE return_quantity IS NULL")
    
    # Rendre les colonnes NOT NULL
    op.alter_column('supplier_order_items', 'is_returned', nullable=False, server_default=None)
    op.alter_column('supplier_order_items', 'return_quantity', nullable=False, server_default=None)
    
    op.create_foreign_key(None, 'supplier_order_items', 'products', ['product_received_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'supplier_order_items', type_='foreignkey')
    op.drop_column('supplier_order_items', 'received_at')
    op.drop_column('supplier_order_items', 'return_date')
    op.drop_column('supplier_order_items', 'return_reason')
    op.drop_column('supplier_order_items', 'return_quantity')
    op.drop_column('supplier_order_items', 'is_returned')
    op.drop_column('supplier_order_items', 'substitution_reason')
    op.drop_column('supplier_order_items', 'product_received_id')
    # ### end Alembic commands ###
