"""add_credit_management_tables

Revision ID: 269c57525a1a
Revises: dd394e2c978c
Create Date: 2025-12-09 12:11:55.985930

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '269c57525a1a'
down_revision: Union[str, None] = 'dd394e2c978c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('credit_transactions', sa.Column('account_id', sa.Integer(), nullable=False))
    op.add_column('credit_transactions', sa.Column('reference_number', sa.String(), nullable=True))
    op.add_column('credit_transactions', sa.Column('last_sync_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('credit_transactions', sa.Column('sync_id', sa.String(), nullable=True))
    op.drop_index(op.f('ix_credit_transactions_credit_account_id'), table_name='credit_transactions')
    op.create_index(op.f('ix_credit_transactions_account_id'), 'credit_transactions', ['account_id'], unique=False)
    op.create_index(op.f('ix_credit_transactions_reference_number'), 'credit_transactions', ['reference_number'], unique=False)
    op.create_index(op.f('ix_credit_transactions_transaction_type'), 'credit_transactions', ['transaction_type'], unique=False)
    op.create_unique_constraint(None, 'credit_transactions', ['sync_id'])
    op.drop_constraint(op.f('credit_transactions_credit_account_id_fkey'), 'credit_transactions', type_='foreignkey')
    op.create_foreign_key(None, 'credit_transactions', 'customer_credit_accounts', ['account_id'], ['id'])
    op.drop_column('credit_transactions', 'reference')
    op.drop_column('credit_transactions', 'credit_account_id')
    op.add_column('customer_credit_accounts', sa.Column('current_balance', sa.Float(), nullable=False))
    op.add_column('customer_credit_accounts', sa.Column('last_sync_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('customer_credit_accounts', sa.Column('sync_id', sa.String(), nullable=True))
    op.drop_index(op.f('ix_customer_credit_accounts_customer_id'), table_name='customer_credit_accounts')
    op.create_index(op.f('ix_customer_credit_accounts_customer_id'), 'customer_credit_accounts', ['customer_id'], unique=False)
    op.create_unique_constraint(None, 'customer_credit_accounts', ['sync_id'])
    op.drop_column('customer_credit_accounts', 'balance')
    op.add_column('payment_breakdowns', sa.Column('last_sync_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('payment_breakdowns', sa.Column('sync_id', sa.String(), nullable=True))
    op.create_unique_constraint(None, 'payment_breakdowns', ['sync_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'payment_breakdowns', type_='unique')
    op.drop_column('payment_breakdowns', 'sync_id')
    op.drop_column('payment_breakdowns', 'last_sync_at')
    op.add_column('customer_credit_accounts', sa.Column('balance', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'customer_credit_accounts', type_='unique')
    op.drop_index(op.f('ix_customer_credit_accounts_customer_id'), table_name='customer_credit_accounts')
    op.create_index(op.f('ix_customer_credit_accounts_customer_id'), 'customer_credit_accounts', ['customer_id'], unique=True)
    op.drop_column('customer_credit_accounts', 'sync_id')
    op.drop_column('customer_credit_accounts', 'last_sync_at')
    op.drop_column('customer_credit_accounts', 'current_balance')
    op.add_column('credit_transactions', sa.Column('credit_account_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('credit_transactions', sa.Column('reference', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'credit_transactions', type_='foreignkey')
    op.create_foreign_key(op.f('credit_transactions_credit_account_id_fkey'), 'credit_transactions', 'customer_credit_accounts', ['credit_account_id'], ['id'])
    op.drop_constraint(None, 'credit_transactions', type_='unique')
    op.drop_index(op.f('ix_credit_transactions_transaction_type'), table_name='credit_transactions')
    op.drop_index(op.f('ix_credit_transactions_reference_number'), table_name='credit_transactions')
    op.drop_index(op.f('ix_credit_transactions_account_id'), table_name='credit_transactions')
    op.create_index(op.f('ix_credit_transactions_credit_account_id'), 'credit_transactions', ['credit_account_id'], unique=False)
    op.drop_column('credit_transactions', 'sync_id')
    op.drop_column('credit_transactions', 'last_sync_at')
    op.drop_column('credit_transactions', 'reference_number')
    op.drop_column('credit_transactions', 'account_id')
    # ### end Alembic commands ###
