"""add_pharmacy_id_to_product_categories

Revision ID: 7dfcc2ca3e12
Revises: ecd9c828ca1f
Create Date: 2025-12-08 17:58:20.929441

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7dfcc2ca3e12'
down_revision: Union[str, None] = 'ecd9c828ca1f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Ajouter la colonne pharmacy_id avec une valeur par défaut (pour les données existantes)
    # On va d'abord créer la colonne comme nullable, puis la remplir, puis la rendre non-nullable
    op.add_column('product_categories', sa.Column('pharmacy_id', sa.Integer(), nullable=True))
    op.add_column('product_categories', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    
    # Pour les catégories existantes, on les associe à la première pharmacie (ou on les supprime si aucune pharmacie)
    # Vérifier d'abord s'il y a des pharmacies
    connection = op.get_bind()
    result = connection.execute(sa.text("SELECT COUNT(*) FROM pharmacies")).scalar()
    
    if result > 0:
        # Associer les catégories existantes à la première pharmacie
        op.execute("""
            UPDATE product_categories 
            SET pharmacy_id = (SELECT id FROM pharmacies ORDER BY id LIMIT 1)
            WHERE pharmacy_id IS NULL
        """)
    else:
        # Si aucune pharmacie, supprimer les catégories existantes
        op.execute("DELETE FROM product_categories WHERE pharmacy_id IS NULL")
    
    # Maintenant rendre la colonne non-nullable
    op.alter_column('product_categories', 'pharmacy_id', nullable=False)
    
    # Supprimer l'ancienne contrainte unique sur name si elle existe
    try:
        op.drop_constraint('product_categories_name_key', 'product_categories', type_='unique')
    except Exception:
        # La contrainte n'existe peut-être pas, continuer
        pass
    
    op.create_index(op.f('ix_product_categories_pharmacy_id'), 'product_categories', ['pharmacy_id'], unique=False)
    op.create_unique_constraint('uq_product_category_pharmacy_name', 'product_categories', ['pharmacy_id', 'name'])
    op.create_foreign_key('fk_product_categories_pharmacy_id', 'product_categories', 'pharmacies', ['pharmacy_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_product_categories_pharmacy_id', 'product_categories', type_='foreignkey')
    op.drop_constraint('uq_product_category_pharmacy_name', 'product_categories', type_='unique')
    op.drop_index(op.f('ix_product_categories_pharmacy_id'), table_name='product_categories')
    op.create_unique_constraint('product_categories_name_key', 'product_categories', ['name'], postgresql_nulls_not_distinct=False)
    op.drop_column('product_categories', 'updated_at')
    op.drop_column('product_categories', 'pharmacy_id')
    # ### end Alembic commands ###
