"""add_credit_management_tables

Revision ID: dd394e2c978c
Revises: 7dfcc2ca3e12
Create Date: 2025-12-09 11:37:15.673918

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dd394e2c978c'
down_revision: Union[str, None] = '7dfcc2ca3e12'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
