"""add_order_url_to_suppliers

Revision ID: f06f59528506
Revises: a9912b1b55af
Create Date: 2025-12-11 13:28:11.899461

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f06f59528506'
down_revision: Union[str, None] = 'a9912b1b55af'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('suppliers', sa.Column('order_url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('suppliers', 'order_url')
    # ### end Alembic commands ###
